[project]
name = "app"
version = "0.1.0"
description = "None"
readme = "README.md"
authors = [{ name = "Developer", email = "" }]
requires-python = ">=3.12"
dependencies = [
    "fletxr==0.1.4.b1",
    "flet[all]>=0.28.3",
]